In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from datetime import datetime
import plotly.express as px
from datetime import datetime

mpl.rc('font',family='Malgun Gothic')

In [23]:
df1 = pd.read_csv('Member_Data.csv', encoding='cp949')
df2 = pd.read_csv('Sales_Data05.csv')
df3 = pd.read_csv('Product_Data.csv')

In [21]:
df1

       Unnamed: 0        회원번호  회원상태 성별   나이   등록카드   결혼   구독여부    주소지 세부주소지
0               0    18764160  정상회원  여   68  농협중앙회   기혼  False  서울특별시   성동구
1               1    18792000  정상회원  남   83  연결앱결제  NaN  False    강원도   강릉시
2               2    18942336  정상회원  여   39   신한은행   기혼  False  인천광역시    중구
3               3    18949760  정상회원  여   73   기업은행  NaN    NaN    강원도   홍천군
4               4    19391488  정상회원  여   52  연결앱결제   기혼  False  대전광역시    중구
...           ...         ...   ... ..  ...    ...  ...    ...    ...   ...
12535       12535  1644957952  정상회원  여   34   신한은행   미혼  False  부산광역시    중구
12536       12536  1645334720  정상회원  남   24   국민카드   미혼  False   전라남도   여수시
12537       12537  1670400000    탈퇴  남   28  연결앱결제  NaN  False  대구광역시    북구
12538       12538  1670606016  정상회원  남   19   하나은행   미혼    NaN   경상남도   밀양시
12539       12539  1670620864  정상회원  남  100   우리은행   기혼    NaN  대구광역시    북구

[12540 rows x 10 columns]

In [15]:
df2

,회원번호,회원상태,구매수량,구매금액,주문일시,배송시작일,배송완료일,사용 적립금,사용 포인트 네이버,주문취소여부,주문시간,제품번호
0,1032097472,정상회원,1.0,7083,2021-01-02,NaN,NaN,0,0,주문취소,오후 12:60,100021783V2_1337
1,1032097472,정상회원,1.0,29865,2021-01-02,2021-01-02,2021-01-02,0,0,NaN,오후 12:60,100022137V2_1606
2,1032097472,정상회원,1.0,23164,2021-01-02,2021-01-02,2021-01-03,0,0,NaN,오후 12:60,100021452V2_1113
3,369152832,정상회원,1.0,16655,2021-01-02,2021-01-02,2021-01-03,0,0,NaN,오후 12:60,10002931V2_708
4,1032097472,정상회원,1.0,8423,2021-01-02,NaN,NaN,0,0,주문취소,오후 12:60,100022085V2_1559
...,...,...,...,...,...,...,...,...,...,...,...,...
668106,1523874368,정상회원,1.0,166554,2021-10-19,2021-10-20,2021-10-20,0,0,NaN,오전 01:00,100022543V2_1912
668107,402835520,정상회원,1.0,12635,2021-10-23,2021-10-23,2021-10-24,0,0,NaN,오전 01:00,10002432V2_327
668108,402835520,정상회원,1.0,7849,2021-10-23,2021-10-23,2021-10-23,0,0,NaN,오전 01:00,100022317V2_1725
668109,1544381312,정상회원,1.0,7275,2021-10-27,2021-10-27,2021-10-28,6270,0,NaN,오전 01:00,10002723V2_563
668110,413164160,정상회원,2.0,20676,2021-10-30,2021-10-30,2021-11-01,0,0,NaN,오전 01:00,100021783V2_1337

In [16]:
df3

                  제품번호      물품명  물품대분류   물품중분류       상품중량
0           100021V2_0    2단무늬컵  식기/편백      자기         1p
1           100022V2_1  7곡딸기롤과자     과자      스낵  100g/10개입
2           100023V2_2     7곡참식   식사대용   선식/생식       700g
3           100024V2_3      가리비   생물수산  패류/갑각류      1.5kg
4           100025V2_3      가리비   생물수산  패류/갑각류        1kg
...                ...      ...    ...     ...        ...
2544  100022545V2_1913   흑임자구름떡      떡     즉석떡       180g
2545  100022546V2_1914   흑임자인절미      떡     즉석떡       150g
2546  100022547V2_1915     흑토마토   과일채소   완숙토마토        1kg
2547  100022548V2_1915     흑토마토   과일채소   완숙토마토      1kg/소
2548  100022549V2_1916     흰밀가루     가루    곡식가루        1kg

[2549 rows x 5 columns]